Added options for plugin
leadvertex/plugin-macros-example pull request #4
Opened 2020-04-03 17:45 UTC by LightFuri

2020-04-05 19:43 UTC, XAKEPEHOK requested changes

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/OptionsForm.php
> +        switch ($number) {
А в чем смысл смешивать реализацию двух разных по сути своей задач в одном классе?

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/OptionsForm.php
> +        switch ($number) {
1 форма = 1 класс

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/OptionsForm.php
> +                    Translator::get('response_options', 'OPTIONS_TITLE'),
Все заголовки, кнопки, описания и все остальное должно быть разными! Считай, мы пишем фикстуры для фронта.  Ты уверен, что на фронте не будет ошибки, в ходе которой название/описание/кнопка будут загружаться только один раз с первой формы?

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/OptionsForm.php
> +        switch ($number) {
Сначала решил что не смотря на это просмотрю код дальше, но нет. Это ужасно, не читаемо, не понятно. **Пропускаю ревью этого файла. Он под снос полностью**

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/SettingsForm.php
> -                ),
Уже не первый раз вижу, что ты так делаешь. И вопрос: зачем? Если в конец массива надо было еще элемент, то вместо простого выделения и нажатия Ctrl+D в phpstorm (чтобы закопипастить сложный фрагмент) сначала потребовалось бы поставить запятую, а потом только выделить нужный текст, закопипастить, и снова зачем-то удалять запятую. PHP поддерживает висящие запятые, и в 7.4 их разрешено использовать даже в аргументах функции. Ладно когда все элемементы на одной строке - это может мешать даже. Но когда каждый элемент с новой строки?

Я лично не вижу ни одного повода убирать висящие запятые. Назови хоть один

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/SettingsForm.php
> +        $staticValidator = function ($values, ListOfEnumDefinition $definition, FormData $form) {
**Я этот коммит не приму. Делай отдельную ветку от мастера.** 
Настраивай перенос строк в git чтобы пушился в \n а не \r\n. Советую checkout as is, commit linux style
http://screenshot.lvcdn.ru/d679b92a99.png

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Plugin.php
> +        return new OptionsForm($number);
Посмотри пример с excel

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Forms/OptionsForm.php
> +                    if (!$options->get('response_options.nullCount', 'true')) {
true - строка?

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Plugin.php
> +                $processResult = 'http://test.uri.com/';
https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%BC%D0%B5%D0%BD%D1%8B_%D0%B4%D0%BB%D1%8F_%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%BE%D0%B2

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Plugin.php
> +                $processResult = 'http://test.uri.com/';
Лучше example.com

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Plugin.php
> +            $process->addError(new Error('Test error'));
Вторым аргументом должен идти номер заказа. Но давай сделаем так, чтобы они шли через одну. Одна с номером, одна без, одна с номером, одна без. Опять же это надо для тестов

2020-04-05 19:43 UTC, XAKEPEHOK commented on src/Plugin.php
> +        $api = new ApiClient($_ENV['LV_API_ENDPOINT'], $_ENV['LV_API_TOKEN']);
Где ты нашел такие переменные?

2020-04-06 17:07 UTC, LightFuri commented on src/Forms/OptionsForm.php
> +        switch ($number) {
Сделал отдельный пулл - #5

2020-04-07 12:10 UTC, XAKEPEHOK approved these changes

2020-04-07 12:10 UTC, merged